export const BIOS_OPTIONS = [
  { id: 1, name: "CPU Turbo Boost", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 2, name: "Hyper-Threading", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 3, name: "Virtualization Technology", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 4, name: "SATA Mode", category: "Advanced", value: "AHCI", options: ["IDE", "AHCI", "RAID"] },
  { id: 5, name: "USB Legacy Support", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled", "Auto"] },
  { id: 6, name: "Fast Boot", category: "Boot", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 7, name: "Secure Boot", category: "Security", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 8, name: "TPM Device", category: "Security", value: "Available", options: ["Available", "Hidden"] },
  { id: 9, name: "Fan Speed Profile", category: "Advanced", value: "Standard", options: ["Standard", "Silent", "Turbo", "Full Speed"] },
  { id: 10, name: "Onboard Audio", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 11, name: "Onboard LAN", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 12, name: "Wake on LAN", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 13, name: "Primary Display", category: "Advanced", value: "Auto", options: ["Auto", "IGFX", "PEG", "PCI"] },
  { id: 14, name: "Internal Graphics", category: "Advanced", value: "Auto", options: ["Auto", "Enabled", "Disabled"] },
  { id: 15, name: "DVMT Pre-Allocated", category: "Advanced", value: "64M", options: ["32M", "64M", "128M", "256M", "512M"] },
  { id: 16, name: "EIST (SpeedStep)", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 17, name: "C-States", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 18, name: "Turbo Mode", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 19, name: "Memory Frequency", category: "Advanced", value: "Auto", options: ["Auto", "2133MHz", "2400MHz", "2666MHz", "3000MHz", "3200MHz"] },
  { id: 20, name: "XMP Profile", category: "Advanced", value: "Disabled", options: ["Disabled", "Profile 1", "Profile 2"] },
  { id: 21, name: "DRAM Voltage", category: "Advanced", value: "1.20V", options: ["1.20V", "1.35V", "1.40V", "1.45V"] },
  { id: 22, name: "CPU Core Voltage", category: "Advanced", value: "Auto", options: ["Auto", "1.10V", "1.15V", "1.20V", "1.25V"] },
  { id: 23, name: "Load Line Calibration", category: "Advanced", value: "Auto", options: ["Auto", "Level 1", "Level 2", "Level 3"] },
  { id: 24, name: "Power Limit 1", category: "Advanced", value: "Auto", options: ["Auto", "65W", "95W", "125W", "Unlimited"] },
  { id: 25, name: "Power Limit 2", category: "Advanced", value: "Auto", options: ["Auto", "150W", "200W", "250W", "Unlimited"] },
  { id: 26, name: "Ring Bus Ratio", category: "Advanced", value: "Auto", options: ["Auto", "40", "42", "44", "46"] },
  { id: 27, name: "AVX Offset", category: "Advanced", value: "0", options: ["0", "-1", "-2", "-3", "-4", "-5"] },
  { id: 28, name: "BCLK Frequency", category: "Advanced", value: "100.00", options: ["100.00", "100.10", "100.20", "101.00"] },
  { id: 29, name: "PCIe Speed", category: "Advanced", value: "Auto", options: ["Auto", "Gen 1", "Gen 2", "Gen 3", "Gen 4"] },
  { id: 30, name: "ASPM Support", category: "Advanced", value: "Disabled", options: ["Disabled", "L0s", "L1", "L0sL1"] },
  { id: 31, name: "ErP Ready", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 32, name: "Restore on AC Power Loss", category: "Advanced", value: "Power Off", options: ["Power Off", "Power On", "Last State"] },
  { id: 33, name: "Keyboard NumLock State", category: "Boot", value: "On", options: ["On", "Off"] },
  { id: 34, name: "Boot Logo Display", category: "Boot", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 35, name: "POST Delay Time", category: "Boot", value: "3 sec", options: ["0 sec", "1 sec", "3 sec", "5 sec", "10 sec"] },
  { id: 36, name: "Wait for 'F1' if Error", category: "Boot", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 37, name: "Option ROM Messages", category: "Boot", value: "Force BIOS", options: ["Force BIOS", "Keep Current"] },
  { id: 38, name: "Interrupt 19 Capture", category: "Boot", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 39, name: "CSM Support", category: "Boot", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 40, name: "Network Stack", category: "Boot", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 41, name: "IPv4 PXE Support", category: "Boot", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 42, name: "IPv6 PXE Support", category: "Boot", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 43, name: "Administrator Password", category: "Security", value: "Not Set", options: ["Set", "Not Set"] },
  { id: 44, name: "User Password", category: "Security", value: "Not Set", options: ["Set", "Not Set"] },
  { id: 45, name: "HDD Password", category: "Security", value: "Not Set", options: ["Set", "Not Set"] },
  { id: 46, name: "Chassis Intrusion", category: "Security", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 47, name: "Intel Platform Trust", category: "Security", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 48, name: "Software Guard Extensions", category: "Security", value: "Software Controlled", options: ["Enabled", "Disabled", "Software Controlled"] },
  { id: 49, name: "Memory Scrambler", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 50, name: "DMI Link ASPM", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 51, name: "PEG Port ASPM", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 52, name: "PCH Thermal Throttling", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 53, name: "IO Voltage", category: "Advanced", value: "Auto", options: ["Auto", "1.05V", "1.10V", "1.15V"] },
  { id: 54, name: "SA Voltage", category: "Advanced", value: "Auto", options: ["Auto", "1.05V", "1.10V", "1.15V"] },
  { id: 55, name: "PLL Termination Voltage", category: "Advanced", value: "Auto", options: ["Auto", "1.0V", "1.1V", "1.2V"] },
  { id: 56, name: "Standby Voltage", category: "Advanced", value: "Auto", options: ["Auto", "1.0V", "1.1V"] },
  { id: 57, name: "DRAM Refresh Rate", category: "Advanced", value: "Auto", options: ["Auto", "1x", "2x", "4x"] },
  { id: 58, name: "CAS Latency (tCL)", category: "Advanced", value: "Auto", options: ["Auto", "14", "15", "16", "17", "18", "19"] },
  { id: 59, name: "RAS to CAS Delay (tRCD)", category: "Advanced", value: "Auto", options: ["Auto", "14", "15", "16", "17", "18", "19"] },
  { id: 60, name: "RAS Precharge (tRP)", category: "Advanced", value: "Auto", options: ["Auto", "14", "15", "16", "17", "18", "19"] },
  { id: 61, name: "Cycle Time (tRAS)", category: "Advanced", value: "Auto", options: ["Auto", "30", "32", "34", "36", "38", "40"] },
  { id: 62, name: "Command Rate", category: "Advanced", value: "Auto", options: ["Auto", "1T", "2T"] },
  { id: 63, name: "Memory Remap", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 64, name: "Graphics Aperture Size", category: "Advanced", value: "256MB", options: ["128MB", "256MB", "512MB", "1024MB"] },
  { id: 65, name: "Primary Video Adapter", category: "Advanced", value: "PCIe", options: ["PCIe", "PCI", "Onboard"] },
  { id: 66, name: "PCI Latency Timer", category: "Advanced", value: "32", options: ["32", "64", "96", "128"] },
  { id: 67, name: "Above 4G Decoding", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 68, name: "Resizable BAR Support", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 69, name: "SR-IOV Support", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 70, name: "VT-d", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 71, name: "IOMMU", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 72, name: "Spread Spectrum", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 73, name: "CPU Fan Step Up", category: "Advanced", value: "0", options: ["0", "1", "2", "3"] },
  { id: 74, name: "CPU Fan Step Down", category: "Advanced", value: "0", options: ["0", "1", "2", "3"] },
  { id: 75, name: "Chassis Fan 1 Profile", category: "Advanced", value: "Standard", options: ["Standard", "Silent", "Turbo", "Full Speed"] },
  { id: 76, name: "Chassis Fan 2 Profile", category: "Advanced", value: "Standard", options: ["Standard", "Silent", "Turbo", "Full Speed"] },
  { id: 77, name: "Water Pump Control", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 78, name: "Thermal Sensor Source", category: "Advanced", value: "CPU", options: ["CPU", "Motherboard", "PCH"] },
  { id: 79, name: "Critical Temperature", category: "Advanced", value: "100C", options: ["90C", "95C", "100C", "105C"] },
  { id: 80, name: "Over-Temperature Protection", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 81, name: "Over-Voltage Protection", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 82, name: "Short Circuit Protection", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 83, name: "Power Supply Idle Control", category: "Advanced", value: "Typical", options: ["Typical", "Low Current"] },
  { id: 84, name: "CPU Core Count", category: "Advanced", value: "All", options: ["All", "1", "2", "4", "6", "8"] },
  { id: 85, name: "SMT Mode", category: "Advanced", value: "Auto", options: ["Auto", "On", "Off"] },
  { id: 86, name: "NX Mode", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 87, name: "SVM Mode", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 88, name: "Core Performance Boost", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 89, name: "Global C-state Control", category: "Advanced", value: "Auto", options: ["Auto", "Enabled", "Disabled"] },
  { id: 90, name: "Power Supply Type", category: "Advanced", value: "ATX", options: ["ATX", "SFX", "TFX"] },
  { id: 91, name: "RGB Lighting in Sleep", category: "Advanced", value: "Off", options: ["On", "Off"] },
  { id: 92, name: "Aura Lighting Effect", category: "Advanced", value: "Rainbow", options: ["Static", "Breathing", "Rainbow", "Off"] },
  { id: 93, name: "POST Beep", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 94, name: "Boot Performance Mode", category: "Advanced", value: "Max Non-Turbo", options: ["Max Battery", "Max Non-Turbo", "Turbo Performance"] },
  { id: 95, name: "Intel Speed Shift", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 96, name: "Race to Halt (RTH)", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 97, name: "Energy Efficient Turbo", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 98, name: "Voltage Optimization", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 99, name: "FCLK Frequency", category: "Advanced", value: "Auto", options: ["Auto", "1600MHz", "1800MHz", "1900MHz"] },
  { id: 100, name: "UCLK Div1 Mode", category: "Advanced", value: "Auto", options: ["Auto", "UCLK=MEMCLK", "UCLK=MEMCLK/2"] },
  { id: 101, name: "Gear Down Mode", category: "Advanced", value: "Auto", options: ["Auto", "Enabled", "Disabled"] },
  { id: 102, name: "Power Down Enable", category: "Advanced", value: "Auto", options: ["Auto", "Enabled", "Disabled"] },
  { id: 103, name: "Bank Group Swap", category: "Advanced", value: "Auto", options: ["Auto", "Enabled", "Disabled"] },
  { id: 104, name: "Bank Group Swap Alt", category: "Advanced", value: "Auto", options: ["Auto", "Enabled", "Disabled"] },
  { id: 105, name: "Data Poisoning", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 106, name: "ECC Support", category: "Advanced", value: "Auto", options: ["Auto", "Enabled", "Disabled"] },
  { id: 107, name: "DRAM Scrub Time", category: "Advanced", value: "Disabled", options: ["Disabled", "1 hour", "24 hours"] },
  { id: 108, name: "Redirect For Return", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 109, name: "L1 Stream HW Prefetcher", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 110, name: "L2 Stream HW Prefetcher", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 111, name: "Hardware Prefetcher", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 112, name: "Adjacent Cache Line Prefetch", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 113, name: "DCU Streamer Prefetcher", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 114, name: "DCU IP Prefetcher", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 115, name: "AES-NI", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 116, name: "SHA Extensions", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 117, name: "RDRAND Support", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 118, name: "SME Support", category: "Advanced", value: "Auto", options: ["Auto", "Enabled", "Disabled"] },
  { id: 119, name: "TSME Support", category: "Advanced", value: "Auto", options: ["Auto", "Enabled", "Disabled"] },
  { id: 120, name: "Data Link Layer Link Active", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 121, name: "Physical Slot Power Limit", category: "Advanced", value: "75W", options: ["10W", "25W", "75W"] },
  { id: 122, name: "Compliance Mode", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 123, name: "Hot Plug Support", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 124, name: "SATA Aggressive Link Power", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 125, name: "ALPM Support", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 126, name: "SATA Port 1 Enable", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 127, name: "SATA Port 2 Enable", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 128, name: "SATA Port 3 Enable", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 129, name: "SATA Port 4 Enable", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 130, name: "External SATA Port", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 131, name: "M.2 Slot 1 Enable", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 132, name: "M.2 Slot 2 Enable", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 133, name: "USB Port 1 Enable", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 134, name: "USB Port 2 Enable", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 135, name: "USB Port 3 Enable", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 136, name: "USB Port 4 Enable", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 137, name: "USB 3.1 Controller", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 138, name: "USB 2.0 Controller", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 139, name: "XHCI Hand-off", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 140, name: "EHCI Hand-off", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 141, name: "USB Mass Storage Driver", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 142, name: "USB Transfer Timeout", category: "Advanced", value: "20 sec", options: ["1 sec", "5 sec", "10 sec", "20 sec"] },
  { id: 143, name: "Device Reset Timeout", category: "Advanced", value: "20 sec", options: ["1 sec", "5 sec", "10 sec", "20 sec"] },
  { id: 144, name: "Device Power-up Delay", category: "Advanced", value: "Auto", options: ["Auto", "Manual"] },
  { id: 145, name: "Serial Port 1", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 146, name: "Parallel Port", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 147, name: "PS/2 Mouse Support", category: "Advanced", value: "Auto", options: ["Auto", "Enabled", "Disabled"] },
  { id: 148, name: "Legacy OS Support", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 149, name: "ACPI Sleep State", category: "Advanced", value: "S3 (Suspend to RAM)", options: ["S1 (POS)", "S3 (Suspend to RAM)"] },
  { id: 150, name: "Power Button Function", category: "Advanced", value: "Instant Off", options: ["Instant Off", "4 Second Delay"] },
  { id: 151, name: "Ring Indicator Wake Up", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 152, name: "RTC Wake Up", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 153, name: "High Precision Timer", category: "Advanced", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 154, name: "Watchdog Timer", category: "Advanced", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 155, name: "System Language", category: "Main", value: "English", options: ["English", "Français", "Deutsch", "Español", "日本語"] },
  { id: 156, name: "System Summary", category: "Main", value: "View", options: ["View"] },
  { id: 157, name: "CPU Temperature Display", category: "Main", value: "Celsius", options: ["Celsius", "Fahrenheit"] },
  { id: 158, name: "BIOS Lock", category: "Security", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 159, name: "Flash Protection", category: "Security", value: "Enabled", options: ["Enabled", "Disabled"] },
  { id: 160, name: "One-step Overclocking", category: "Advanced", value: "Disabled", options: ["Disabled", "Level 1", "Level 2", "Extreme"] },
  { id: 161, name: "Quantum Computing Mode", category: "Extreme", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 162, name: "Time Travel Debugger", category: "Extreme", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 163, name: "Sentient AI Co-processor", category: "Extreme", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 164, name: "Gravity Manipulation", category: "Extreme", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 165, name: "Reality Distortion Field", category: "Extreme", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 166, name: "Infinite Improbability Drive", category: "Extreme", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 167, name: "Coffee Machine Interface", category: "Extreme", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 168, name: "Telepathy Link", category: "Extreme", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 169, name: "Dark Matter Cooling", category: "Extreme", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 170, name: "Warp Drive Core", category: "Extreme", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 171, name: "Flux Capacitor", category: "Extreme", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 172, name: "Matrix Simulation", category: "Extreme", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 173, name: "Ghost in the Shell", category: "Extreme", value: "Disabled", options: ["Enabled", "Disabled"] },
  { id: 174, name: "Universe Reset", category: "Extreme", value: "Disabled", options: ["Enabled", "Disabled"] }
];
